### ISSUE TITLE
When I use setFieldValue, buffers not update

### ISSUE THREAD

**Issue by mittus** [bigin/ItemManager_2.0#17]
setFieldValue don't work with buffers and I can't get new value from getSimpleItems.

Example (field "price" value = 300):
```php
$imanager = imanager();
$itemMapper = $imanager->getItemMapper();

$item = $imanager->getItem(5, 1);
$item->setFieldValue('price', 450);
$item->save();
var_dump($item->fields->price->value); // it's ok, give 450
// next time
$itemMapper->alloc(5);
$items = $itemMapper->getSimpleItems('active=1');
foreach($items as $item) {
    var_dump($item->price); // have old value 300
}
```

At this example in admin page I see new value (450), but I can't get this with getSimpleItems, becouse information on buffers file have old data (300).

**Comment by bigin** [comment]
`SimpleItem != Item`

That's correct, SimpleItem object is not a real-time reflection of the Item object. You should first save the item as a SimpleItem object:
```php
// Save Item & SimpleItem object
if($newItem->save()) {
    $itemMapper->simplify($newItem);
    $itemMapper->save();
}
```
;-)
