### ISSUE TITLE
Depencency of file upload field on Bootstrap CDN and blueimp.github.io

### ISSUE THREAD

**Issue by VIPStephan** [bigin/ItemManager_2.0#2]
It kinda sucks that the file upload field requires a connection to third-party CDNs/sources. It would be better if they were included in the plugin core or relinquished in the first place (especially Bootstrap gives me the shudders, for it is unnecessary bloatware).
You never know if/when a third-party service is down, and then you stand there with non-functioning software for no good reason.

**Comment by bigin** [comment]
Fixed
