### ISSUE TITLE
Admin styles conflict when I use ItemManager with SpecialPages

### ISSUE THREAD

**Issue by mittus** [bigin/ItemManager_2.0#5]
Hello!

When I use ItemManager with i18n SpecialPages, I have deffect in styles on the SpecialPages plugin edit page.

List all my plugins: http://prntscr.com/ekza17
Deffect on SpecialPages: http://prntscr.com/ekzaa1
If ItemManager is deactivated (normal styles): http://prntscr.com/ekzagw

**Comment by bigin** [comment]
yes, there seems to be some CSS conflict - Thank you!

**Comment by bigin** [comment]
fixed

**Comment by mittus** [comment]
I think, this have JS conflict too, becouse general options in the special pages need be open'd as default.

This now: http://prntscr.com/el2l05
With deactivated ItemManager: http://prntscr.com/el2leh

**Comment by bigin** [comment]
hmm... indeed, I will look at it soon, thanks. And just for your information - you don't really need Special Pages if you use ItemManager. All of these features are already implemented. Do you know ImExtraFields plugin? https://github.com/bigin/ImExtraFields

**Comment by mittus** [comment]
@bigin no, I don't know about ImExtraFields. Tank you for advice, I will surely learn this!!

**Comment by bigin** [comment]
so, the hidden tab issue in SpecialPages should be fixed now ;-)

**Comment by mittus** [comment]
Now it work! Thank you!! This problem has long time troubled me :))
