### ISSUE TITLE
Problem with field "WYSIWYG editor"

### ISSUE THREAD

**Issue by mittus** [bigin/ItemManager_2.0#8]
When I use field with wysiwyg editor, has problem with tags.

1. Screen from ItemManager: http://prntscr.com/gnx5v4
`<img alt="" src="/data/uploads/laureates/2017/molnia_infrastructure_05.jpg" style="width: 284px; height: 190px;" />`
2. Screen from site: http://prntscr.com/gnx76e
`<img alt="&quot;&quot;" src="&quot;/data/uploads/laureates/2017/img_5408.jpg&quot;" style="&quot;height:" 190px;&#34;="">`

When I replase at code all " to ', image generated correct, but after again edit this them, wysiwyg display again " instead ' and if I save this, images displayed with wrong code.

**Comment by bigin** [comment]
I'll check it out soon, thank you for the info

**Comment by bigin** [comment]
Yes, the quotes are replaced, which is a good thing, I think.

But what can be said against use of htmlspecialchars_decode(); when outputting the editor field value? 
Look, like this, for example:

```php
echo stripslashes(htmlspecialchars_decode($iitem->editor, ENT_QUOTES));
```

**Comment by mittus** [comment]
It's right, thank you for help!!!
