### ISSUE TITLE
File upload field problems

### ISSUE THREAD

**Issue by mittus** [bigin/ItemManager_2.0#9]
**File upload field problems**
I use PHP 5.6 with nginx. With php 7 I not get first problem, but second problem is remains.
1. When I try upload image, I see Server Error and don't see thumbnail
![screenshot_1](https://user-images.githubusercontent.com/711179/44953816-3b204500-ae99-11e8-82f7-6dfd6d90fdc1.png)
![screenshot_2](https://user-images.githubusercontent.com/711179/44953822-673bc600-ae99-11e8-9fce-7b03fdd929ff.png)
![screenshot_3](https://user-images.githubusercontent.com/711179/44953825-8a667580-ae99-11e8-89d0-c401b257d04b.png)
2. After update page, it I click on the delete button, image don't delete, but folder /server/php was deleted.
![screenshot_4](https://user-images.githubusercontent.com/711179/44953862-fb0d9200-ae99-11e8-933c-aa77209f01b6.png)

**Comment by bigin** [comment]
Thanks for reporting. Could you please separate these issues? thx

**Comment by mittus** [comment]
+

**Comment by bigin** [comment]
I have tested nginx, there are some issues here, so using ItemManager with nginx is currently not recommended. Thank you for reporting.

**Comment by mittus** [comment]
Problems with read index.php I was fix:
```
    # fix index.php
    location ~ ^/(plugins/imanager/upload/server/php)/ {
        try_files $uri $uri/ /index.php?$uri&$args;
    }
```
Other problems I can't fix. Hope that soon nginx will work. Than'k You for help!!

**Comment by bigin** [comment]
Here's what you could try: Change this line [https://github.com/bigin/ItemManager_2.0/blob/master/imanager/upload/server/php/UploadHandler.php#L100](https://github.com/bigin/ItemManager_2.0/blob/master/imanager/upload/server/php/UploadHandler.php#L100) to `'delete_type' => 'POST',` that might solve the problem with deleting, but I'm afraid there are more things that are causing trouble.

**Comment by mittus** [comment]
I can access to DELETE method on nginx with this:
```
server {
...
    dav_access user:rw group:rw all:rw;
    dav_methods PUT DELETE MKCOL COPY MOVE;
    create_full_put_path on;
```

But if I change delete_type to POST, I have correct deleting Image.

Now I have problems only with uploading files. I see 500 Server Error and this Error in data/other/logs/errorlog.txt: `[04-Sep-2018 17:54:02 Europe/Moscow] NoDecodeDelegateForThisImageFormat `JPEG' @ error/constitute.c/ReadImage/501`, then uploaded images haven't thumbnails.

**Comment by mittus** [comment]
Yes it's have problem only with PHP 5.6. With PHP 7 upload work!

**Comment by bigin** [comment]
Hmm, just tested with Ngnix and PHP 5.6 on MAMP and the download works without problems for me. 
Did you get any error messages in your browser console on the item editor page before uploading?

**Comment by bigin** [comment]
I think it's a server configuration problem, because everything works for me, try to check your nginx error.log

**Comment by bigin** [comment]
This looks like that's an imagick error

**Comment by bigin** [comment]
imagick isn't installed properly?

**Comment by bigin** [comment]
Probably imagick is running without support for the image format that you're trying to open JPEG.
Try a other format, png for example

**Comment by mittus** [comment]
It's true. I have problem with imagick plugin. I will fix that. Than'k you for answer!!
![screenshot_9](https://user-images.githubusercontent.com/711179/45147613-9b7af380-b1c5-11e8-87c0-eb78347bd2f6.png)

**Comment by bigin** [comment]
Thank you for reporting the issues ;-)

**Comment by mittus** [comment]
I was fix problem with imagick, but now have new problem ))) It actual for different images
![screenshot_10](https://user-images.githubusercontent.com/711179/45160399-a6e01600-b1e9-11e8-962a-ed704cbadc5b.png)

**Comment by mittus** [comment]
This problem actual, becouse `$new_width` in 1019 line is an Object. Now I try fix that :)
![screenshot_11](https://user-images.githubusercontent.com/711179/45161644-a432f000-b1ec-11e8-86c0-1f929bbd57bb.png)

**Comment by mittus** [comment]
Did this, and now it works 😆 
![screenshot_12](https://user-images.githubusercontent.com/711179/45161946-2fac8100-b1ed-11e8-9abc-ad5d67d2d9f4.png)

**Comment by bigin** [comment]
Hmm OK, I need to check that, I may have to fix that, thx!

**Comment by mittus** [comment]
Now it works. Thank You!!
